export const UPDATE_UNIVERSITY_SEARCH_RECORD_IDS = 'UPDATE UNIVERSITY SEARCH RECORD IDS';
export const SET_SEARCH_MODE_STATUS = 'SET SEARCH MODE STATUS';
export const SET_SEARCH_MODE_LOADER_STATUS = 'SET SEARCH MODE LOADER STATUS';
export const RESET_AND_CLOSE_SEARCH = 'RESET AND CLOSE SEARCH';
export const BIND_SEARCH_TEXT = 'BIND SEARCH TEXT';
export const UNIVERSITY_SEARCH_NO_RECORDS = 'UNIVERSITY SEARCH NO RECORDS';
