export const UPDATE_OPPORTUNITY_SEARCH_RECORD_IDS = 'opportunities/UPDATE OPPORTUNITY SEARCH RECORD IDS';
export const SET_SEARCH_MODE_STATUS = 'opportunities/SET SEARCH MODE STATUS';
export const SET_SEARCH_MODE_LOADER_STATUS = 'opportunities/SET SEARCH MODE LOADER STATUS';
export const RESET_AND_CLOSE_SEARCH = 'opportunities/RESET AND CLOSE SEARCH';
export const BIND_SEARCH_TEXT = 'opportunities/BIND SEARCH TEXT';
export const OPPORTUNITY_SEARCH_NO_RECORDS = 'opportunities/OPPORTUNITY SEARCH NO RECORDS';
