export const ADD_PROFILE_RECORDS_WITH_META_DATA = 'profiles/ADD_PROFILE_RECORDS_WITH_META_DATA';
export const ADD_PROFILE_RECORDS_WITHOUT_META_DATA = 'profiles/ADD_PROFILE_RECORDS_WITHOUT_META_DATA';
export const PROFILE_CONNECT_UPDATE = 'profiles/PROFILE_FOLLOW_UPDATE';
