export const ADD_PAGE_RECORDS_WITH_META_DATA = 'pages/ADD_PAGE_RECORDS_WITH_META_DATA';
export const ADD_PAGE_RECORDS_WITHOUT_META_DATA = 'pages/ADD_PAGE_RECORDS_WITHOUT_META_DATA';
export const PAGE_FOLLOW_UPDATE = 'pages/PAGE_FOLLOW_UPDATE';
export const ADD_VIEWPAGE_PAGE_RECORDS = 'pages/ADD_VIEWPAGE_PAGE_RECORDS';
